# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='description',
            field=models.TextField(default='N/A', max_length=250),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
