# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_portal', '0002_auto_20171108_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quizes',
            new_name='quize',
        ),
    ]
