# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_portal', '0003_auto_20171108_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quize',
            new_name='quiz',
        ),
    ]
